### ISSUE TITLE
publish the package to nuget

### ISSUE THREAD

**Issue by KoenigLear** [mlhpdx/seekable-s3-stream#4]
It would be really helpful if you published your package to nuget.

https://docs.microsoft.com/en-us/nuget/nuget-org/publish-a-package#:~:text=Sign%20into%20your%20nuget.org,%2C%20select%20Select%20Scopes%20%3E%20Push.

**Comment by mlhpdx** [comment]
Indeed.  I wish that Microsoft would convey a strategy for integrating, or at least rationalizing, GH packages and Nuget.  I'll look at adding "dual publishing" to the build actions.

**Comment by mlhpdx** [comment]
It's been way too long, but the package is on Nuget now. 

https://www.nuget.org/packages/SeekableS3Stream#readme-body-tab
